#!/bin/csh

if ("$1" == "-v") then
  set vbose=1
  set tswitches="-cvf"
  shift
else
  set vbose=0
  set tswitches="-cf"
endif

while ( "$1" != "" )
  if ($vbose) then
    echo "arc: [tarring "$1"]"
  endif
  if (! -e tars) then
    if ($vbose) then
      echo "arc: [creating directory "$cwd"/tars]"
    endif
    mkdir tars
  endif
  tar $tswitches tars/$1.tar $1
  if ($vbose) then
    echo "arc: [compressing "tars/$1.tar"]"
  endif
  compress tars/$1.tar
  if (-e tars/$1.tar.Z  || -e tars/$1.tar) then
    if ($vbose) then
      echo "arc: [removing source directory]"
    endif
    rm -rf $1
  else
    echo "arc: [error in creating"tars/$1.tar.Z"]"
    echo "arc: [source directory not removed]"
  endif
  shift
end
