#!/bin/sh
# copy primary selection to the clipboard
#xclip -o | xclip -selection clipboard
if [ x"$1" = x"r" ]; then
  pbpaste -pboard general -Prefer txt | xclip -selection primary
else
  xclip -o | pbcopy
fi
