#!/bin/sh
set -v
set -x
old=$1
new=$2
for x in $old/*.java; do
fname=`filename $x`.java
any=`diff -wq $old/$fname $new/$fname`
if [ x"$any" != x ]; then
  echo "******************************************************************************************* $fname **********************************************************************************************************************************************************"
  paralleldiff $old/$fname $new/$fname
fi
done
