#!/bin/bash
dir1=$1
dir2=$2


function diff1 {
#  dos2unix -q $dir1/$1
#  dos2unix -q $dir2/$1
  if [ -r $dir1/$1 -a -r $dir2/$1 ]; then
    any=`diff -wq $dir1/$1 $dir2/$1`
    if [ x"$any" != x ]; then
    echo "************************************************paralleldiff $dir1/$1 $dir2/$1*************************************************************************"
      paralleldiff $dir1/$1 $dir2/$1
      echo ""
    fi
  elif [ ! -r $dir1/$1 ]; then
    echo "++++++++++++++++++++++++++++++++++++++++++++++++ NEW: $dir2/$1"
  fi
}
function diffList {
  for x in "$@"; do
    diff1 $x
  done
}

there=$PWD
cd $dir1
java_src=`find src -name *.java -print`
java_tst=`find tests -name *.java -print`
sqlf_src=`find sqlfire/java/engine -name *.java -print`
conf_tst=`find tests -name *.conf -print`
bt_tst=`find tests -name *.bt -print`
xml_files=`find . -name "*.xml" -print`
cd $there

diffList $java_src
diffList $sqlf_src
echo "**************************************************************"
echo "*"
echo "*"
echo "*"
echo "*"
echo "*"
echo "* T E S T S"
echo "*"
echo "*"
echo "*"
echo "*"
echo "*"
echo "*"
echo "**************************************************************"
diffList $java_tst
echo "**************************************************************"
echo "*"
echo "*"
echo "*"
echo "*"
echo "*"
echo "* C O N F"
echo "*"
echo "*"
echo "*"
echo "*"
echo "*"
echo "*"
echo "**************************************************************"
diffList $conf_tst
echo "**************************************************************"
echo "*"
echo "*"
echo "*"
echo "*"
echo "*"
echo "* B A T T E R Y"
echo "*"
echo "*"
echo "*"
echo "*"
echo "*"
echo "*"
echo "**************************************************************"
diffList $bt_tst
echo "**************************************************************"
echo "*"
echo "*"
echo "*"
echo "*"
echo "*"
echo "* X M L"
echo "*"
echo "*"
echo "*"
echo "*"
echo "*"
echo "*"
echo "**************************************************************"
diffList $xml_files
