#!/bin/bash
if [ x"$1" = x"-d" ]; then
  debug=1
  shift 1
fi
log=${1:-buildLinux.log}
files=`svn status | grep ^[C] | cut -c8-`
rm -f conflicts.txt
echo $files >conflicts.txt
if [ x"$debug" = x1 ]; then
  echo $files
else
  exec emx -s "<<<<<" $files
fi
