#!/bin/bash
if [ x"$1" = x"-d" ]; then
  debug=1
  shift 1
fi
log=${1:-buildLinux.log}
files=`grep \[javac\] $log | grep "\.java:" | grep -v warning | grep -v "Will create one" | cut -c 13- | cut -d ":" -f 1 | sort | uniq`
if [ x"$debug" = x1 ]; then
  echo $files
else
  exec emx $log $files
fi
