#!/bin/bash

if [ -r /usr/bin/fgrep ]; then
  FGREP=/usr/bin/fgrep
elif [ -r /bin/fgrep ]; then
  FGREP=/bin/fgrep
else
  FGREP=grep
fi

if [ x"$2" != x ]; then

  find . -type f -follow -exec $FGREP -li "$1" "$2" $3 $4 {} \;

else

  find . -type f -follow -exec $FGREP -l "$1" $2 $3 {} \;

fi
