#!/bin/sh
function mkdh {
  if [ x"${1}" != x  -a ! -d ${1} ]; then
    mkdh `dirname ${1}`
    mkdir ${1}
  fi
}
there=`pwd`
recursive=""
if [ x"$1" == "-r" ]; then
  recursive="-r"
  thedir=${2}
  thefile=""
else
  thedir=`dirname ${1}`
  thefile=`basename ${1}`
fi
cd /
mkdh $thedir
cd $there
set -x
set -v
scp $recursive trout.gemstone.com:$thedir/$thefile $thedir/$thefile
