#!/bin/sh
if [ -r ../gemfire-assembly ]; then
  cd ..
fi
if [ -r gemfire ]; then
  cd gemfire
  git pull
  cd ..
fi
if [ -r geode ]; then
  cd geode
  git pull geode `git branch --show-current`
  cd ..
fi

