#!/bin/sh
if [ -r ../gemfire-assembly ]; then
  cd ..
fi
if [ -r gemfire ]; then
  cd gemfire
  git pull
  cd ..
fi
if [ -r geode ]; then
  cd geode
  git pull
  cd ..
fi
if [ -r gemfire-assembly ]; then
  cd gemfire-assembly
  git pull
  cd ..
fi

