#!/bin/bash
if [ -d gemfire-assembly ]; then
  echo "resetting geode-assembly"
  sleep 1
  cd gemfire-assembly
  git reset --hard HEAD
  cd ..
fi
if [ -d geode ]; then
  echo "resetting open source"
  sleep 1
  cd geode
  git reset --hard HEAD
  cd ..
fi
if [ -d gemfire ]; then
  echo "resetting gemfire"
  cd gemfire
  git reset --hard HEAD
  cd ..
fi
if [ -d .git ]; then
  echo "resetting $PWD"
  git reset --hard HEAD
  done
fi

