#!/bin/bash
t=tests.bt
if [ -r dunit-tests.bt ]; then
  t=dunit-tests.bt
fi
testfile=${1:-$t}
#rm -f batterytest.bt batterytest.log
echo "batch testing $testfile"
at now <<END
#runbatterytest -DJPROBE=$JPROBE -DJPROBE_HOME=$JPROBE $testfile
runbatterytest $testfile
END
#sleep 2
#if [ -r oneliner.txt ]; then
#  tail -f oneliner.txt
#fi
