#!/bin/sh
if [ -r /usr/bin/fgrep ]; then
  fgrep=/usr/bin/fgrep
else
  fgrep=/bin/fgrep
fi
if [ x"$1" = x"-i" ]; then
find . -name "*.java" -follow -exec $fgrep -li "$2" $3 $4 {} \;
else
find . -name "*.java" -follow -exec $fgrep -l "$1" $2 $3 {} \;
fi
