#!/bin/sh
cd /gcm/where/machine_use
if [ x"$1" = x"-e" ]; then
  edit=1
  shift
else
  edit=0
fi
#if [ -r /usr/bin/newgrp ]; then
#  newgrp engineering
#fi
if [ x"$1" = x"-g" ]; then
  grep=1
  shift
  files=`grep -li "$@" *`
else
  files=""
  for x in "$@"; do
    if [ -r $x ]; then
      files="$files $x"
    else
      echo "no machine_use file for $x"
      sleep 2
      exit
    fi
  done
fi
if [ $edit = "1" ]; then
  $VISUAL $files
else
  less $files
fi

