#!/bin/sh
# omitted: kili oin jade1c
cmd=uptime
if [ x"$1" = x"-c" ]; then
  cmd="$1"
  shift 1
fi

machines="balrog bilbo biscuit carlos ent frodo hobbes loot merry"
machines="$machines oin pippin tidepool jade1a jade1b jade1c jade1d jade1e"

machines=`java -cp /home/bschuchardt/usr/classes ReachableHosts $machines`

if [ $? -gt 0 ]; then
  echo $machines
  exit 1
fi
for x in $machines; do
echo -n "${x}	:"; ssh -x -n ${x} $cmd
done

