#!/bin/sh
if [ x"$1" = x ]; then
machines="w1-gst-dev01 w1-gst-dev02 w1-gst-dev03 w1-gst-dev04 w1-gst-dev05 w1-gst-dev06 w1-gst-dev07 w1-gst-dev08 w1-gst-dev09 w1-gst-dev26 w1-gst-dev27 w1-gst-dev28"
machines="$machines ent frodo"
else
machines="$*"
fi
for x in $machines; do
  #echo $x 1>&2
  rdef=`ssh $x cat /proc/sys/net/core/rmem_default`
  rmax=`ssh $x cat /proc/sys/net/core/rmem_max`
  wdef=`ssh $x cat /proc/sys/net/core/wmem_default`
  wmax=`ssh $x cat /proc/sys/net/core/wmem_max`
  tcpr=`ssh $x cat /proc/sys/net/ipv4/tcp_rmem`
  tcpw=`ssh $x cat /proc/sys/net/ipv4/tcp_wmem`
  echo "$x	udp read $rdef/$rmax write $wdef/$rmax  tcp $tcpr : $tcpw"
done
