#!/bin/sh
echo "============================================================"
echo "GEODE DISTRIBUTED TESTS"
echo "============================================================"
polljenkins.py -start 997 -job Geode_develop_DistributedTests

echo "============================================================"
echo "GEODE INTEGRATION TESTS"
echo "============================================================"
polljenkins.py -start 1077 -job Geode_develop_IntegrationTests

echo "============================================================"
echo "GEODE UNIT TESTS"
echo "============================================================"
polljenkins.py -start 208 -job Geode_develop_UnitTests

echo "============================================================"
echo "GEMFIRE DISTRIBUTED TESTS"
echo "============================================================"
polljenkins.py -start 298 -job GemFire_develop_DistributedTests -jira internal

echo "============================================================"
echo "GEMFIRE INTEGRATION TESTS"
echo "============================================================"
polljenkins.py -start 322 -job GemFire_develop_IntegrationTests -jira internal

echo "============================================================"
echo "GEMFIRE UNIT TESTS"
echo "============================================================"
polljenkins.py -start 149 -job GemFire_develop_UnitTests -jira internal

echo "============================================================"
echo "GEMFIRE SMOKE TESTS"
echo "============================================================"
polljenkins.py -start 116 -job GemFire_develop_SmokeTests -jira internal

echo "============================================================"
echo "GEMFIRE MORESMOKE TESTS"
echo "============================================================"
polljenkins.py -start 224 -job GemFire_develop_MoreSmoke -jira internal

