#!/bin/bash

defns=""
while [ "${1:0:2}" == "-D" ]; do
  defns="$defns $1"
  shift 1
done
#echo "definitions = \'${defns}\'"

if [ x$1 == x ]; then
  if [ -r tests.bt ]; then
    file=tests.bt
  else
    file=`ls *.bt | head -1`
  fi
else
  file=$1
fi

blcl=$build/tests/classes

target=$file
if [ ! -r $file ]; then
  if [ -r $blcl/$file ]; then
    target=$blcl/$file
  else
     echo "can't find test file '$file' here or in the build directory"
    exit 1
  fi
fi

#cho "cleaning"
#cleanhydra

#GREPLOGS="-DgrepLogs=true"
#REMOVEPASSES="-DremovePassedTest=true"
#TESTJVM="-DtestJVM=path to java executable"
MOVEDIRS="-DmoveRemoteDirs=true"

echo "running test $file"

CLASSPATH=$GEMFIRE/lib/gemfire.jar:$GEMFIRE/lib/antlr.jar:$blcl
CLASSPATH=$CLASSPATH:$JAVA_HOME/lib/tools.jar
CLASSPATH=$CLASSPATH:$GEMFIRE/lib/mail.jar
#CLASSPATH=$CLASSPATH:$GEMFIRE/lib/spring-core*.jar:$GEMFIRE/lib/spring-shell*.jar:$GEMFIRE/lib/jansi.jar:$GEMFIRE/lib/jline.jar
CLASSPATH=$CLASSPATH:/gcm/where/java/junit/junit3.8.1/junit.jar:/gcm/where/java/JavaConTest/Lib/ConTest.jar

export CLASSPATH

export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$build/hidden/lib

java -DGEMFIRE=$GEMFIRE \
  -Dgemfire.home=$GEMFIRE \
  $GREPLOGS $REMOVEPASSES $TESTJVM $MOVEDIRS \
  -DJTESTS=$blcl \
  -DnumTimesToRun=1 \
  -DreportToWRT=false \
  -DnukeHungTest=true \
  -DtestFileName=$target \
  $defns \
  batterytest.BatteryTest

if [ -r oneliner.txt ]; then
  grep " F " oneliner.txt
  grep " H " oneliner.txt
else
  echo "could not locate oneliner.txt"
fi

