#! /bin/sh
if [ -d /usr/sccs ]; then
PATH=/usr/sccs:$PATH
elif [ -d /usr/ccs/bin ]; then
PATH=/usr/ccs/bin:$PATH
fi
while [ "$1" != "" ]; do
  echo $1 "---------------"
  delta ccs/s.$1
  if [ $? -eq 0 ]; then
     echo $1 updated in ccs
     get -r ccs/s.$1
     if [ $? -eq 0 ]; then
       echo $1 fetched for reading
     fi
  fi
  shift
done
