#! /bin/bash

# watchbt noexit - never exits
# watchbt msg - uses xmessage to notify when done

if [ -r dunit-tests.prop ]; then
  echo "this is really a dunit directory"
  sleep 2
  exec watchdunit
fi
if [ x"$1" = x"noexit" ]; then
  noexit="y"
fi
typeset -i numParentDirs
typeset -i testCount
testCount=`grep -c .conf batterytest.bt`
typeset -i numfailures
typeset -i numhangs
typeset -i numpass
typeset -i numrun
typeset -i current
typeset -i numParentDirs

#function grantorHangs {
#  typeset -i numG
#  typeset -i count
#  numG=0
#  count=0
#  for x in `grep " H " oneliner.txt`; do
#    if [ $count -eq 3 ]; then
#      found=`grep -l ElderRecovery $x/bg*.log`
#      if [ x"$found" != x ]; then
#        numG=$((numG + 1))
#      fi
#      count=0
#    else
#      count=$((count + 1))
#    fi
#  done
#  echo "grantor hangs=$numG"
#}

# figure out the last field of a oneliner.txt entry so the entries
# can be trimmed later on
lastOnelinerField=`pwd -P | cut -d/ --output-delimiter=" " -f1-50 | wc -w`
lastOnelinerField=$((lastOnelinerField + 2))

# reset colors on exit (/home/bschuchardt/usr/bin50/color)
trap "color fg default bg default" EXIT

while [ 0 ]
do
  numpass=`grep -c " P " oneliner.txt`
  numhangs=`grep -c " H " oneliner.txt`
  numfailures=`grep -c " F " oneliner.txt`
  numrun=`grep -c "RESULT: " batterytest.log`
  current=$numrun+1
  curtest=`grep "DIR=" batterytest.log | tail -1 | cut -d "=" -f 3`
  curtest=`filename $curtest`
  curtask2=`grep Assigning $curtest/taskmaster*.log | tail -1`
  curtask=`tail -1 $curtest/taskmaster*.log`

  clear
  color fg white bg blue
  free | head -2
  echo ""
#  color fg white bg blue
  uptime
  echo ""
  color fg normal bg normal
  echo -n "total=$testCount  tests run=$numrun  "
  color bg default fg green
  echo -n "passed=$numpass  "
  if [ $numfailures -gt 0 ]; then
    color bg default fg red
  fi
  echo -n "failed=$numfailures  "
  if [ $numhangs -gt 0 ]; then
    color bg default fg red
  fi
  echo "hung=$numhangs"
  echo ""
  color fg default bg default
  echo -n "current test ($current):   "
  color fg magenta
  echo $curtest
  echo ""
  color fg blue
  echo $curtask2
  echo ""
  echo $curtask
  if [ $testCount -gt 1 -o $numrun -eq $testCount ]; then
    echo ""
    color fg default bg default
    echo "oneliner.txt:"
    tail -4 oneliner.txt | cut -d" " -f 2-100 | stripfront | cut -d"/" --output-delimiter=" " -f1,$lastOnelinerField
  fi
  if [ x"$noexit" = x ]; then
    if [ $numrun -eq $testCount ]; then
      beep
      beep
      sleep 1
      beep
      beep
      if [ x"$1" == x"msg" ]; then
        hn=`hostname`
        xmessage "$hn is done"&
      fi
      exit 0
    fi
  fi
  sleep 10
done
