#!/bin/bash
exec 2>&1
exec | tee dunit.log
COVER=""
if [ $1 == -cover ]; then
  COVER=-PcodeCoverage
  shift
fi
test=$1
shift
gr $COVER -x javadoc -x docs -DacceptanceTest.single=$test  acceptanceTest "$@"

