#!/bin/sh
#  precheckin.sh closed-branch open-branch

LANG=en_US.ISO_8859-1
export LANG

if [ x"$2" == x ]; then
  echo "testFeatureBranch closedBranch openBranch"
  exit 2
fi

clbranch=$1
obranch=$2

cd ~/devel/gemfire-deployments
git pull

set -v
set -x
cd precheckin
./deploy_developer_pipeline.sh -e bschuchardt@pivotal.io \
-c $clbranch \
-g $obranch \
-t bschuchardt-precheckin
