#!/bin/sh
# concDestroyAll <-n>
cd ~/devel/gemfire-deployments
git pull
cd ./precheckin
dashn=""
if [ x"$1" == "x-n" ]; then
  dashn="-N"
  shift 1
fi
pipelines=`./list_developer_pipelines.sh | grep bschuchardt`
for x in $pipelines; do
  echo $x
  ./destroy_developer_pipeline.sh $dashn $x
done
