#!/bin/sh
#  precheckin.sh geode-diff tag-number

LANG=en_US.ISO_8859-1
export LANG

cp $1 ~/devel/gemfire-deployments/precheckin/diff.txt

cd ~/devel/gemfire-deployments
git pull

set -v
cd precheckin
./deploy_developer_pipeline.sh -e bschuchardt@pivotal.io -G diff.txt \
-t bschuchardt-precheckin$2
