#!/bin/sh
#  precheckin.sh geode-diff tag-number

LANG=en_US.ISO_8859-1
export LANG

cp ./closed.diff ~/devel/gemfire-deployments/precheckin/
cp ./open/open.diff ~/devel/gemfire-deployments/precheckin/

cd ~/devel/gemfire-deployments
git pull

set -v
cd precheckin
./deploy_developer_pipeline.sh -e bschuchardt@pivotal.io -C closed.diff -G open.diff \
-t bschuchardt-precheckin$1
