#!/bin/sh
# concTestFeatureBranch closed-branch open-branch <precheckin-number>

LANG=en_US.ISO_8859-1
export LANG

if [ x"$2" == x ]; then
  echo "testFeatureBranch closedBranch openBranch <tag-number>"
  exit 2
fi

clbranch=$1
obranch=$2

cd ~/devel/gemfire-deployments
git pull

set -v
set -x
cd precheckin
./deploy_developer_pipeline.sh -e bschuchardt@pivotal.io \
-c $clbranch \
-g $obranch \
-t bschuchardt-precheckin${3}
