#!/bin/sh
# concTestFeatureBranch branch <precheckin-number>

LANG=en_US.ISO_8859-1
export LANG

if [ x"$1" == x ]; then
  echo "testFeatureBranch openBranch <tag-number>"
  exit 2
fi

obranch=$1

cd ~/devel/gemfire-deployments
git pull

set -v
set -x
cd precheckin
./deploy_developer_pipeline.sh -e bschuchardt@pivotal.io \
-g $obranch \
-t bschuchardt-precheckin${2}
