#!/bin/sh
#  precheckin.sh closed-branch open-branch geode-diff

LANG=en_US.ISO_8859-1
export LANG

if [ x"$3" == x ]; then
  echo "precheckinBranch.sh closedBranch openBranch diffFile"
  exit 2
fi

clbranch=$1
obranch=$2
cp $3 ~/devel/gemfire-deployments/precheckin/diff.txt

cd ~/devel/gemfire-deployments
git pull

set -v
set -x
cd precheckin
#-r git@github.com:gemfire/geode-support.git \
./deploy_developer_pipeline.sh -e bschuchardt@pivotal.io \
-c $clbranch \
-g $obranch \
-G diff.txt \
-t bschuchardt-precheckin


