#!/bin/sh
here=$PWD
rm -f unfinishedTests.txt
for x in `ff *-progress.txt`; do
  pushd `dirname $x` >/dev/null
  echo $PWD >>$here/unfinishedTests.txt
  grep "Starting test" *progress.txt | cut -d " " -f 6-7 | sort >starting.srt
  grep "Completed test" *progress.txt | cut -d " " -f 6-7 | sort >completed.srt
  diff starting.srt completed.srt >>$here/unfinishedTests.txt
  popd >/dev/null
done
cd $here
${VISUAL:-vim} -p unfinishedTests.txt
