#!/bin/bash
cd $layer/closed
gr -x javadoc -x regressionDistTar -x regressionDistZip -x srcDistTar \
 -x srcDistZip -x distZip -x distTar -Dskip.tests=true \
 assemble installDist testClasses createHydraClassesDir

