#!/bin/bash
cd $layer/closed
gr --stacktrace --parallel -x javadoc -x docs -x checkpom -x spotlessCheck\
 -x pmdMain -Dskip.tests=true build installDist

#gr --stacktrace --parallel -x javadoc -x regressionDistTar -x regressionDistZip -x srcDistTar \
# -x srcDistZip -x distZip -x distTar -Dskip.tests=true \
# assemble installDist testClasses createHydraClassesDir

#rm -f pivotalgf-assembly/gemfire-test/hydraAdditionalJars

#mkdir -p pivotalgf-assembly/gemfire-test

#ln -s gemfire-test/build/hydraAdditionalJars \
# pivotalgf-assembly/gemfire-test/

