#!/bin/bash

if [ -r ./gradlew ]; then
  exec ./gradlew --no-daemon "$@" -Dcomposite
elif [ -r ../gradlew ]; then
  exec ../gradlew --no-daemon "$@" -Dcomposite
else
  echo "can't find ./gradlew or ../gradlew"
  exit 2
fi

