#!/bin/sh
btfile=$1
if [ ! -r $btfile ]; then
  echo $btfile not found
  exit 2
fi
there=$PWD
cd $layer/gemfire/closed
./gradlew runHydraTest -PhydraResultDir=$there -PhydraTestFileName=$btfile
cd $there
