#!/bin/bash
if [ ! -d ./closed/gemfire-test ]; then
  echo "please run this script from your top-level checkout directory"
  exit 2
fi

homedir=$PWD

checkunittests | semx -&

cd closed/build/reports/combined
httpServer
